name: 'uber_dw'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +database: "UBER_DW"

  sources:
    +schema: "RAW"

  stage:
    +schema: "DW"     # stg_trip lives in DW

  dim:
    +schema: "DW"     # all dim tables now in DW

  fact:
    +schema: "DW"     # fact_trip in DW
