name: 'uber_dw'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ----------- THE FIX -----------
models:
  # Prevent auto schema combinations like DW_DW or DW_STAGE
  +schema: "{{ target.schema }}"
  +database: "UBER_DW"

  sources:
    +schema: "RAW"

  stage:
    +schema: "STAGE"

  dim:
    +schema: "DW"

  fact:
    +schema: "DW"
# --------------------------------